using Nathan_ICTPRG547_Assignment;

Console.WriteLine("Subject Test");
Subject subject1 = new Subject();
Console.WriteLine("subject1");
Console.WriteLine(subject1);
subject1.SubjectCode = "ICT123";
subject1.SubjectName = "Programming";
subject1.SubjectCost = 150.6;
Console.WriteLine("subject1 code " + subject1.SubjectCode);
Console.WriteLine("subject1 name " + subject1.SubjectName);
Console.WriteLine("subject1 cost " + subject1.SubjectCost);
Console.WriteLine("number of subjects " + Subject.NumSubjects);
Subject subject2 = new Subject("ICT456", "Programming2", 500);
Console.WriteLine("subject2");
Console.WriteLine(subject2);
Console.WriteLine("number of subjects " + Subject.NumSubjects);
Console.WriteLine("");
Console.ReadKey();

Console.WriteLine("Enrollment Test");
Enrollment enrollment1 = new Enrollment();
Console.WriteLine("enrollment1");
Console.WriteLine(enrollment1);
enrollment1.EnrollmentDateEnrolled = "06/05/2023";
enrollment1.EnrollmentGrade = "NS";
enrollment1.EnrollmentSemester = 1;
enrollment1.EnrollmentSubject = subject1;
Console.WriteLine("enrollment1 dateEnrolled " + enrollment1.EnrollmentDateEnrolled);
Console.WriteLine("enrollment1 grade " + enrollment1.EnrollmentGrade);
Console.WriteLine("enrollment1 semester " + enrollment1.EnrollmentSemester);
Console.WriteLine("enrollment1 subject " + enrollment1.EnrollmentSubject);
Console.WriteLine("number of enrollments " + Enrollment.NumEnrollments);
Enrollment enrollment2 = new Enrollment("05/09/2025", "P", 2);
Console.WriteLine("enrollment2");
Console.WriteLine(enrollment2);
Console.WriteLine("number of enrollments " + Enrollment.NumEnrollments);
Enrollment enrollment3 = new Enrollment("05/06/2024", "P", 1,subject2);
Console.WriteLine("enrollment3");
Console.WriteLine(enrollment3);
Console.WriteLine("number of enrollments " + Enrollment.NumEnrollments);
Console.WriteLine("");
Console.ReadKey();

Console.WriteLine("Address Test");
Address address1 = new Address();
Console.WriteLine("address1");
Console.WriteLine(address1);
address1.AddressStreetNum = 1;
address1.AddressStreetName = "Bob St";
address1.AddressSuburb = "Suburb1";
address1.AddressPostcode = 1234;
address1.AddressState = "South Australia";
Console.WriteLine("address1 streetNum " + address1.AddressStreetNum);
Console.WriteLine("address1 streetName " + address1.AddressStreetName);
Console.WriteLine("address1 suburb " + address1.AddressSuburb);
Console.WriteLine("address1 postcode " + address1.AddressPostcode);
Console.WriteLine("address1 state " + address1.AddressState);
Console.WriteLine("number of address " + Address.NumAddress);
Address address2 = new Address(6, "John St", "Suburb2",5678,"New South Wales");
Console.WriteLine("address2");
Console.WriteLine(address2);
Console.WriteLine("number of address " + Address.NumAddress);
Console.WriteLine("");
Console.ReadKey();

Console.WriteLine("Person Test");
Person person1 = new Person();
Console.WriteLine("person1");
Console.WriteLine(person1);
person1.PersonName = "Bob";
person1.PersonEmail = "bob@bob";
person1.PersonPhoneNumber = "01234678";
person1.PersonAddress = address1;
Console.WriteLine("person1 name " + person1.PersonName);
Console.WriteLine("person1 email " + person1.PersonEmail);
Console.WriteLine("person1 phoneNumber " + person1.PersonPhoneNumber);
Console.WriteLine("person1 address " + person1.PersonAddress);
Console.WriteLine("number of people " + Person.NumPeople);
Person person2 = new Person("Gerald", "gerald@gerald", "03748327");
Console.WriteLine("person2");
Console.WriteLine(person2);
Console.WriteLine("number of people " + Person.NumPeople);
Person person3 = new Person("Jeff", "jeff@jeff", "0123898347", address2);
Console.WriteLine("person3");
Console.WriteLine(person3);
Console.WriteLine("number of people " + Person.NumPeople);
Console.WriteLine("");
Console.ReadKey();

Console.WriteLine("Student Test");
Student student1 = new Student();
Console.WriteLine("student1");
Console.WriteLine(student1);
student1.StudentID = "003755";
student1.StudentProgram = "Programming1";
student1.StudentDateRegistered = "21/05/4394";
student1.StudentEnrollment = enrollment1;
Console.WriteLine("student1 studentID " + student1.StudentID);
Console.WriteLine("student1 program " + student1.StudentProgram);
Console.WriteLine("student1 dateRegistered " + student1.StudentDateRegistered);
Console.WriteLine("student1 enrollment " + student1.StudentEnrollment);
Console.WriteLine("number of students " + Student.NumStudents);
Student student2 = new Student("029484", "Programming2", "12/05/1999");
Console.WriteLine("student2");
Console.WriteLine(student2);
Console.WriteLine("number of students " + Student.NumStudents);
Student student3 = new Student("038465", "Programming3", "29/01/2020", enrollment3,person3.PersonName,person3.PersonEmail,person3.PersonPhoneNumber,person3.PersonAddress);
Console.WriteLine("student3");
Console.WriteLine(student3);
Console.WriteLine("number of students " + Student.NumStudents);
Console.WriteLine("");
Console.ReadKey();